defaults:
  - _self_
  - jax/state_sampler: uniform


replay_buffer:
  capacity: 1e6
batch_size: 256
discount: 0.99
safety_discount: 0.99
polyak_rate: 5e-3
initial_log_lagrangians: [0.]
prefill: 500
actor:
  n_layers: 2
  hidden_size: 128
  init_stddev: 5.
critic:
  n_layers: 2
  hidden_size: 128
actor_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
critic_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
lagrangians_optimizer:
  lr: 3e-4
  eps: 1e-8
  clip: 1e6
