defaults:
  - mujoco_playground_base
task_name: AlohaPegInsertDistill
task_params:
  ctrl_dt: 0.05
  sim_dt: 0.005
  episode_length: 160
  action_repeat: 1
  action_scale: 0.02
  action_history_length: 4
  max_obs_delay: 4
  reset_buffer_size: 10
  vision: true
  vision_config:
    gpu_id: 0
    render_batch_size: 1024
    randomization_fn: null
    render_width: 64
    render_height: 64
    enabled_geom_groups: [1, 2, 5]
    use_rasterizer: false
    enabled_cameras: [4, 5]
  obs_noise:
    depth: true
    brightness: [0.5, 2.5]
    grad_threshold: 0.05
    noise_multiplier: 10
    obj_pos: 0.015
    obj_vel: 0.015
    obj_angvel: 0.2
    gripper_box: 0.015
    obj_angle: 7.5
    robot_qpos: 0.1
    robot_qvel: 0.1
    eef_pos: 0.02
    eef_angle: 5.0
  reward_config:
    scales:
      peg_insertion: 8
      obj_rot: 0.5
    sparse:
      success: 0
      drop: -10
      final_grasp: 10
    reg:
      robot_target_qpos: 1
      joint_vel: 1
      grip_pos: 0.5

train_params: {}

eval_params: {}
