defaults:
  - mujoco_playground_base

task_name: SafeCartpoleSwingup
task_params:
  slider_position_bound: 0.25
  action_repeat: 1
  ctrl_dt: 0.01
  episode_length: 1000
  sim_dt: 0.01
  vision: false

# Sample uniformly around the nominal value
train_params:
  pole_length: [-0.25, 0.25]
  pole_mass: [0., 0.]

eval_params:
  pole_length: [-0.25, 0.25]
  pole_mass: [-0.05, 0.05]
