defaults:
  - mujoco_playground_base

task_name: SafeCartpoleSwingup
task_params:
  slider_position_bound: 0.25

# Sample uniformly around the nominal value
train_params:
  pole_length: [-0.25, 0.25]
  pole_mass: [-0.05, 0.05]

eval_params:
  pole_length: [0, 1]
  pole_mass: [-0.05, 0.05]
