domain_name: "extremeparkour"
task_name: "extremeparkour"

checkpoint: -1
cols: null
compute_device_id: 0
daggerid: null
debug: false
delay: false
device: "cuda:0"
distill_only_heading: false
draw: false
experiment_name: null
exptid: "000-00-aa"
flex: false
graphics_device_id: 0
headless: true
hitid: null
horovod: false
load_run: null
mask_obs: false
max_iterations: null
no_wandb: true
nodelay: false
num_envs: null
num_threads: 0
physics_engine: "SimType.SIM_PHYSX" # This will cause problems
physx: false
pipeline: "gpu"
proj_name: "parkour_new"
resume: false
resumeid: null
rl_device: "cuda:0"
rows: null
run_name: null
save: false
seed: null
sim_device: "cuda:0"
sim_device_id: 0
sim_device_type: "cuda"
slices: 0
subscenes: 0
task: "go1"
task_both: false
teacher: null
use_camera: false
use_gpu: true
use_gpu_pipeline: true
use_jit: false # Can we enable this? TODO: Beni find out
use_latent: false
web: false