defaults:
  - mujoco_playground_base
task_name: PandaPickCubeCartesianExtended
task_params:
  use_ball: false
  use_x: false
  ctrl_dt: 0.05
  sim_dt: 0.005
  episode_length: 200
  action_repeat: 1
  action_scale: 0.005
  reward_config:
    reward_scales:
      gripper_box: 4.0
      box_target: 8.0
      no_floor_collision: 0.25
      no_box_collision: 0.05
      robot_target_qpos: 0.0
    action_rate: -0.0005
    no_soln_reward: -0.01
    lifted_reward: 0.5
    success_reward: 2.0
  vision: false
  vision_config:
    gpu_id: 0
    render_batch_size: 1024
    render_width: 84
    render_height: 84
    use_rasterizer: false
    enabled_geom_groups: [0, 1, 2]
  obs_noise:
    brightness: [1.0, 1.0]
  box_init_range: 0.05
  success_threshold: 0.05
  action_history_length: 1

train_params: {}

eval_params: {}
