defaults:
  - mujoco_playground_base
task_name: Go1JoystickFlatTerrain
task_params:
  Kd: 0.5
  Kp: 35.0
  action_repeat: 1
  action_scale: 0.5
  command_config:
    a:
      - 1.5
      - 0.8
      - 1.2
    b:
      - 0.9
      - 0.25
      - 0.5
  ctrl_dt: 0.02
  episode_length: 1000
  history_len: 1
  noise_config:
    level: 1.0
    scales:
      gravity: 0.05
      gyro: 0.2
      joint_pos: 0.03
      joint_vel: 1.5
      linvel: 0.1
  pert_config:
    enable: false
    kick_durations:
      - 0.05
      - 0.2
    kick_wait_times:
      - 1.0
      - 3.0
    velocity_kick:
      - 0.0
      - 3.0
  reward_config:
    max_foot_height: 0.1
    scales:
      action_rate: -0.01
      ang_vel_xy: -0.05
      dof_pos_limits: -1.0
      energy: -0.001
      feet_air_time: 0.1
      feet_clearance: -2.0
      feet_height: -0.2
      feet_slip: -0.1
      lin_vel_z: -0.5
      orientation: -5.0
      pose: 0.5
      stand_still: -1.0
      termination: -1.0
      torques: -0.0002
      tracking_ang_vel: 0.5
      tracking_lin_vel: 1.0
    tracking_sigma: 0.25
  sim_dt: 0.004
  soft_joint_pos_limit_factor: 0.95

train_params: null
eval_params: null
