defaults:
  - safety_gym_base

task_name: go_to_goal
task_params: {}

train_params:
  damping:
    x: [0., 0.]
    y: [0., 0.]
    z: [0., 0.]
  gear:
    x: [0.75, 1.5]
    z: [1., 1.]

eval_params:
  damping:
    x: [0., 0.]
    y: [0., 0.]
    z: [0., 0.]
  gear:
    x: [0.75, 1.5]
    z: [0.5, 2.]
