defaults:
  - safety_gym_base

task_name: go_to_goal
task_params: {}

train_params:
  damping:
    x: [1., 1.]
    y: [1., 1.]
    z: [1., 1.]
  gear:
    x: [-0.2, 0.2]
    z: [-0.1, 0.1]

eval_params:
  damping:
    x: [0.75, 1.25]
    y: [0.75, 1.25]
    z: [0.9, 1.1]
  gear:
    x: [-0.2, 0.2]
    z: [-0.1, 0.1]
