defaults:
  - brax_base
  - _self_

backend: mjx
task_name: humanoid_safe
task_params:
  angle_tolerance: 2.
  terminate_when_unhealthy: true
  healthy_z_range: [1.0, 2.0]

# Sample uniformly around the nominal value
train_params:
  friction: [-0.05, 0.05]
  gain_hip:
    x: [-20., 20.]
    y: [-20., 20.]
    z: [-60., 60.]
  gain_knee: [-40., 40.]
  gear_hip:
    x: [-20., 20.]
    y: [-20., 20.]
    z: [-60., 60.]
  gear_knee: [-40., 40.]

eval_params:
  friction: [-0.05, 0.05]
  gain_hip:
    x: [-20., 20.]
    y: [-20., 20.]
    z: [-60., 60.]
  gain_knee: [-40., 40.]
  gear_hip:
    x: [-20., 20.]
    y: [-20., 20.]
    z: [-60., 60.]
  gear_knee: [-40., 40.]