defaults:
  - mujoco_playground_base

task_name: SafeHumanoidWalk
task_params:
  action_repeat: 1
  ctrl_dt: 0.025
  episode_length: 1000
  sim_dt: 0.0025
  vision: false
  angle_tolerance: 0.

# Sample uniformly around the nominal value
train_params:
  friction: [-0.05, 0.05]
  gear_hip:
    x: [-25., 25.]
    y: [-25., 25.]
    z: [-75., 75.]
  gear_knee: [-50., 50.]

eval_params:
  friction: [-0.05, 0.05]
  gear_hip:
    x: [-25., 25.]
    y: [-25., 25.]
    z: [-75., 75.]
  gear_knee: [-50., 50.]
