defaults:
  - brax_base
  - _self_

backend: mjx
task_name: humanoid_safe
task_params: 
  max_force: 10.
  terminate_when_unhealthy: true
  healthy_z_range: [1.0, 2.0]
  

# Sample uniformly around the nominal value
train_params:
  mass: [0., 1.] # mass of the pole, not cart.
  gear: [5., 20.]

eval_params:
  mass: [0., 1.]
  gear: [5., 20.]
