defaults:
  - mujoco_playground_base

task_name: SafeHumanoidWalk
task_params:
  action_repeat: 1
  ctrl_dt: 0.025
  episode_length: 1000
  sim_dt: 0.0025
  vision: false
  angle_tolerance: 0.

# Sample uniformly around the nominal value
train_params:
  friction: [-0.05, 0.05]
  gear_hip:
    x: [-1., 1.]
    y: [-1., 1.]
    z: [-3., 3.]
  gear_knee: [-2., 2.]

eval_params:
  friction: [-0.05, 0.05]
  gear_hip:
    x: [-1., 1.]
    y: [-1., 1.]
    z: [-3., 3.]
  gear_knee: [-2., 2.]
