defaults:
  - mujoco_playground_base

task_name: SafeHumanoidWalk
task_params:
  action_repeat: 1
  ctrl_dt: 0.025
  episode_length: 1000
  sim_dt: 0.0025
  vision: false
  angle_tolerance: 2.

# Sample uniformly around the nominal value
train_params:
  friction: [-0.05, 0.05]
  gear_hip:
    x: [-5., 5.]
    y: [-5., 5.]
    z: [-15., 15.]
  gear_knee: [-10., 10.]

eval_params:
  friction: [-0.05, 0.05]
  gear_hip:
    x: [-5., 5.]
    y: [-5., 5.]
    z: [-15., 15.]
  gear_knee: [-10., 10.]
