defaults:
  - mujoco_playground_base

task_name: PendulumSwingup
task_params:
  action_repeat: 1
  ctrl_dt: 0.01
  episode_length: 1000
  sim_dt: 0.01
  vision: false

# Sample uniformly around the nominal value
train_params:
  pendulum_length: [0.0, 0.0]

eval_params:
  pendulum_length: [-0.25, 0.25]
