defaults:
  - mujoco_playground_base

task_name: SafeQuadrupedRun
task_params:
  angle_tolerance: -20.
  action_repeat: 1
  ctrl_dt: 0.02
  episode_length: 1000
  sim_dt: 0.005
  vision: false

# Sample uniformly around the nominal value
train_params:
  torso: [-250, 250]
  friction: [0., 0.]
  damping: [0., 0.]
  gear:
    lift: [-20., 20.]
    yaw: [-20., 20.]
    extend: [-20., 20.]

eval_params:
  torso: [-250, 250]
  friction: [0., 0.]
  damping: [0., 45.]
  gear:
    lift: [-20., 20.]
    yaw: [-20., 20.]
    extend: [-20., 20.]
