defaults:
  - mujoco_playground_base

task_name: SafeQuadrupedRun
task_params:
  angle_tolerance: -20.
  action_repeat: 1
  ctrl_dt: 0.02
  episode_length: 1000
  sim_dt: 0.005
  vision: false

# Sample uniformly around the nominal value
train_params:
  torso: [0., 0.]
  friction: [0., 0.]
  damping: [0., 0.]
  gear:
    lift: [0.9, 1.1]
    yaw: [0.9, 1.1]
    extend: [0.9, 1.1]

eval_params:
  torso: [-250, 250]
  friction: [-0.95, 0.95]
  damping: [0., 0.]
  gear:
    lift: [0.9, 1.1]
    yaw: [0.9, 1.1]
    extend: [0.9, 1.1]
