defaults:
  - _self_
  - train_car_params: car_2_blend
  - eval_car_params: car_2_blend

domain_name: rccar
task_name: rccar
dt: 0.033
encode_angle: true
ctrl_cost_weight: 0.005
margin_factor: 20.0
max_throttle: 0.4
use_obs_noise: false
obstacles:
  - [2., 0, 0.35] # x, y, radius
  - [1., -1., 0.35]
  - [1., 1., 0.35]
observation_delay: 0
action_delay: 0
sliding_window: 0
