defaults:
  - _self_
  - train_car_params: car_2_blend
  - eval_car_params: car_2_blend

domain_name: rccar
task_name: rccar
dt: 0.033
obstacles:
  - [0.75, -0.55, 0.25]
  - [0.75, -0.15, 0.25]
  - [0.75, 0.25, 0.25]
  - [0.75, 0.65, 0.25]
observation_delay: 0
action_delay: 0
sliding_window: 0
sample_init_pose: true
control_penalty_scale: 0.01