defaults:
  - brax_base
  - _self_

backend: mjx
task_name: walker2d_safe
task_params:
  angle_tolerance: 2.
  forward_reward_weight: 1.0
  ctrl_cost_weight: 0.001
  healthy_reward: 1.0
  terminate_when_unhealthy: true
  healthy_z_range: [0.8, 2.0]
  healthy_angle_range: [-1.0, 1.0]
  reset_noise_scale: 0.005
  exclude_current_positions_from_observation: true

# Sample uniformly around the nominal value
train_params:
  friction: [-0.05, 0.05]
  thigh: [-20., 20.]
  leg: [-20., 20.]
  foot: [-20., 20.]

eval_params:
  friction: [-0.05, 0.05]
  thigh: [-20., 20.]
  leg: [-20., 20.]
  foot: [-20., 20.]
