defaults:
  - _self_
  - environment: rccar
  - override /environment/train_car_params: car_2_blend
  - override /environment/eval_car_params: car_2_blend

hydra:
  run:
    dir: ${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/${hydra.job.name}
    subdir: ${hydra.job.override_dirname}/seed=${training.seed}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - training.seed
          - wandb
    chdir: true

environment:
  action_delay: 3
  observation_delay: 3
  sliding_window: 3
  dt: 0.03333333



log_dir: outputs
baseline_trajectory: /home/yarden/ethz/rl/safe-sim2real/data/baseline_check_data.pkl
check_trajectory: /home/yarden/ethz/rl/safe-sim2real/data/baseline_check_data.pkl
action_repeat: 1
episode_length: 100
