defaults:
  - environment: rccar
  - override /environment/train_car_params: car_2_blend
  - override /environment/eval_car_params: car_2_blend
  - _self_

hydra:
  run:
    dir: ${log_dir}/hardware_rccar/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - training.seed
          - wandb
    chdir: true

log_dir: outputs

writers:
  - wandb
  - jsonl
  - stderr

wandb:
  group: null
  notes: null
  name: ${hydra:job.override_dirname}

environment:
  sliding_window: 5

seed: 0
num_trajectories: 100
episode_length: 250
action_repeat: 1
safety_budget: 1
safe: false
car_id: 2
port_number: 4
control_frequency: 120.
policy_id: null
playback_policy: null
out_path_name: null
no_controller: false
