defaults:
  - _self_
  - agent: sac
  - environment: rccar

hydra:
  run:
    dir: ${log_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${log_dir}/${hydra.job.name}
    subdir: ${hydra.job.override_dirname}/seed=${training.seed}
  job:
    config:
      override_dirname:
        exclude_keys:
          - log_dir
          - training.seed
          - wandb
    chdir: true

log_dir: outputs

writers:
  - wandb
  - jsonl
  - stderr

wandb:
  group: null
  notes: null
  name: ${hydra:job.override_dirname}

jit: true

training:
  safe: true
  safety_budget: 25
  seed: 0
  num_evals: 25
  episode_length: 1000
  num_envs: 2048
  num_eval_envs: 128
  action_repeat: 1
  render: true
  num_timesteps: 1000000
  privileged: false
  train_domain_randomization: true
  eval_domain_randomization: true
  store_policy: true