name: awac_mpc

learning_rate: 3e-4
critic_learning_rate: 3e-4
discounting: 0.99
batch_size: 256
normalize_observations: true
reward_scaling: 1.0
tau: 0.005
min_replay_size: 8192
max_replay_size: 1000000
grad_updates_per_step: 512
num_critic_updates_per_actor_update: 1
deterministic_eval: true
reset_on_eval: true
planner_eval: false
env_reset_every_steps: 0

rollout_length: 1
mpo_eta: 1.0
mpo_eta_epsilon: 0.1
mpo_eta_min: 1e-3
mpo_eta_opt_maxiter: 10
mpo_log_prob_min: -100.0
mpo_num_action_samples: 16
use_baseline_value: true
use_planner_transitions: true
planner_actor_single_random_trajectory: false
planner_actor_winner_trajectory: false
planner_actor_max_imagined_steps: 3
planner_actor_imagined_transitions_per_root: 8
policy_target_tau: 0.001
actor_grad_clip_norm: 1.0
critic_grad_clip_norm: 1.0

policy_hidden_layer_sizes: [128, 128]
value_hidden_layer_sizes: [512, 512]
activation: swish
use_bro: true
n_critics: 2

controller_kwargs:
  num_samples: 16
  horizon: 1
  zoh_steps: 1
  temperature: 0.8
  iterations: 1
  terminal_action_samples: 1
