num_timesteps: 10000000
prefill: 5000
discount: 0.99
batch_size: 256
reward_scaling: 1.0
num_grad_steps_per_step: 1
polyak_rate: 0.005
replay_buffer:
  capacity: 1e6
actor:
  n_layers: 2
  hidden_size: 128
critic:
  n_layers: 2
  hidden_size: 128
actor_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
critic_optimizer:
  lr: 3e-4
  eps: 1e-5
  clip: 0.5
lagrangians_optimizer:
  lr: 3e-4
  eps: 1e-8
  clip: 1e6
initial_log_lagrangians: [0.]
