nominal:
  use_blend: 0.0
  m: 1.65
  l_f: 0.13
  l_r: 0.17
  angle_offset: 0.0
  b_f: 2.58
  b_r: 5.0
  blend_ratio_lb: 0.01
  blend_ratio_ub: 0.01
  c_d: 0.0
  c_f: 1.2
  c_m_1: 8.0
  c_m_2: 1.5
  c_r: 1.27
  d_f: 0.02
  d_r: 0.017
  i_com: 0.01
  steering_limit: 0.3

bounds:
  use_blend: [0.0, 0.0]
  m: [1.6, 1.7]
  l_f: [0.11, 0.15]
  l_r: [0.15, 0.19]
  angle_offset: [-0.15, 0.15]
  b_f: [2.4, 2.6]
  b_r: [2.0, 8.0]
  blend_ratio_lb: [0.4, 0.4]
  blend_ratio_ub: [0.5, 0.5]
  c_d: [0.01, 0.01]
  c_f: [1.2, 1.2]
  c_m_1: [6.0, 10.0]
  c_m_2: [1.0, 1.8]
  c_r: [1.27, 1.27]
  d_f: [0.02, 0.02]
  d_r: [0.017, 0.017]
  i_com: [0.01, 0.1]
  steering_limit: [0.15, 0.4]
