nominal:
  use_blend: 1.0
  m: 1.65
  l_f: 0.13
  l_r: 0.17
  angle_offset: 0.0
  b_f: 2.75
  b_r: 5.0
  blend_ratio_lb: 0.001
  blend_ratio_ub: 0.017
  c_d: 0.0
  c_f: 1.45
  c_m_1: 8.2
  c_m_2: 1.25
  c_r: 1.3
  d_f: 0.4
  d_r: 0.3
  i_com: 0.06
  steering_limit: 0.6

bounds:
  use_blend: [1.0, 1.0]
  m: [1.6, 1.7]
  l_f: [0.125, 0.135]
  l_r: [0.165, 0.175]
  angle_offset: [-0.15, 0.15]
  b_f: [2.0, 4.0]
  b_r: [3.0, 10.0]
  blend_ratio_lb: [0.0001, 0.1]
  blend_ratio_ub: [0.0001, 0.2]
  c_d: [0.0, 0.0]
  c_f: [1.1, 2.0]
  c_m_1: [6.5, 10.0]
  c_m_2: [1.0, 1.5]
  c_r: [0.4, 2.0]
  d_f: [0.25, 0.6]
  d_r: [0.15, 0.45]
  i_com: [0.03, 0.18]
  steering_limit: [0.4, 0.75]
