nominal:
  use_blend: 0.0
  m: 1.65
  l_f: 0.13
  l_r: 0.17
  angle_offset: 0.0
  b_f: 2.58
  b_r: 5.0
  blend_ratio_lb: 0.01
  blend_ratio_ub: 0.01
  c_d: 0.0
  c_f: 1.2
  c_m_1: 8.0
  c_m_2: 1.5
  c_r: 1.27
  d_f: 0.02
  d_r: 0.017
  i_com: 0.01
  steering_limit: 0.3

bounds:
  use_blend: [0.0, 0.0]
  m: [1.6, 1.7]
  l_f: [0.125, 0.135]
  l_r: [0.165, 0.175]
  angle_offset: [-0.5, 0.5]
  b_f: [2.7, 2.8]
  b_r: [4.5, 5.5]
  blend_ratio_lb: [0.0001, 0.0005]
  blend_ratio_ub: [0.015, 0.02]
  c_d: [0.0, 0.2]
  c_f: [1.2, 1.5]
  c_m_1: [5.0, 10.0]
  c_m_2: [1.0, 2.0]
  c_r: [1.0, 1.5]
  d_f: [0.02, 0.5]
  d_r: [0.01, 0.9]
  i_com: [0.01, 0.1]
  steering_limit: [0.1, 0.75]
